export const HttpResponse = {
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    PASSWORD_INCORRECT:"Incorrect password, try again",
    NO_ACCESS_TOKEN: "Token not provided",
    NO_REFRESH_TOKEN: "Refresh token not provided",
    NO_TOKEN: "Token not provided",
    NO_DECODED_TOKEN: "Couldn't decode token",
    CATEGORY_EXIST: "Category already exists",
    CATEGORY_INSERT_ERROR: "Error inserting category",
    CATEGORY_FETCH_ERROR: "Couldn't fetch categories",
    CATEGORY_NOT_FOUND: "Category not found",
    CATEGORY_UPDATE_ERROR: "Couldn't update category",
    CATEGORY_DELETE_ERROR: "Couldn't delete category",
    CATEGORY_DELETED: "Category deleted successfully",
    USER_ID_REQUIRED: "User ID is required",
    COURSE_ID_REQUIRED: "Course ID is required",
    COURSE_EXIST_WISHLIST: "Course already in wishlist",
    COURSE_ADDED_WISHLIST: "Course added to wishlist",
    WISHLIST_NOT_FOUND: "Wishlist not found",
    COURSE_NOT_FOUND_WISHLIST: "Course not found in wishlist",
    COURSE_REMOVED_WISHLIST: "Course removed from wishlist",
    PUBLIC_ID_NOT_FOUND: "Cloudinary publicId not found",
    COURSE_EXIST_ENROLLED: "Course already enrolled",
    COURSE_ENROLLED: "Course enroled successfully",
    ENROLLED_COURSES_NOT_FOUND: "No enrolled courses found"
}