services:
  nginx-rtmp:
    build: .
    ports:
      - "1935:1935"
      - "8080:8080"
    restart: always
    volumes:
      - "./hls:/tmp/hls"
    networks:
      - live-network

  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    depends_on:
      - nginx-rtmp
    restart: always
    privileged: true
    networks:
      - live-network

  live-service:
    build: .
    ports:
      - "5005:5005"
    environment:
      - LIVE_SERVICE="http://nginx-rtmp:5005"
    depends_on:
      - nginx-rtmp
    networks:
      - live-network

networks:
  live-network:
    driver: bridge
