services:
  # 🚀 FRONTEND SERVICE
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway
    environment:
      - VITE_BASE_API_URL=http://api-gateway:5000/api
      - VITE_BASE_URL=http://api-gateway:5000
      - VITE_GOOGLE_CLIENT_ID=value
      - VITE_STRIPE_PUBLIC_KEY=value
    networks:
      - app-network

  # 🚀 API GATEWAY
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - user-service
      - blog-service
      - course-service
      - live-service
      - notification-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
      - USER_SERVICE_URL=http://user-service:5002
      - COURSE_SERVICE_URL=http://course-service:5003
      - BLOG_SERVICE_URL=http://blog-service:5004
      - LIVE_SERVICE_URL=http://live-service:5005
      - NOTIFICATION_SERVICE_URL=http://notification-service:5006
      - API_GATEWAY_KEY=996940d97b77a0bb9f7dbfbf6e8d8af5dfa6ca47250a3b2846d0272ca6eb741f
      - JWT_SECRET=d45659e5d171e2ed2ba45ff0fd76eb68a8e627576e8529be335cbd192973b21cf1c34702b3ff9afab6bde6454bd05abec322741f95bf4242c8baffaf48ed2a18
    networks:
      - app-network

  # 🚀 AUTH SERVICE
  auth-service:
    build: ./backend/auth-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-service
      - JWT_ACCESS_SECRET=d45659e5d171e2ed2ba45ff0fd76eb68a8e627576e8529be335cbd192973b21cf1c34702b3ff9afab6bde6454bd05abec322741f95bf4242c8baffaf48ed2a18
      - JWT_REFRESH_SECRET=71a0ffce065819b7147f467d28a0f7cf4181e2dd7f731d763a8cde357d9978519b11f3a68e60842c7a96a9879c04cebeac4a71f50ad9fd89752da5888ca4805d
      - FRONTEND_URL=http://frontend:5173
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
      - API_GATEWAY_KEY=996940d97b77a0bb9f7dbfbf6e8d8af5dfa6ca47250a3b2846d0272ca6eb741f
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  # 🚀 USER SERVICE
  user-service:
    build: ./backend/user-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-service
      - GOOGLE_CLIENT_ID=value
      - GOOGLE_CLIENT_SECRET=value
      - BACKEND_URL=http://api-gateway:5000/api
      - JWT_ACCESS_SECRET=d45659e5d171e2ed2ba45ff0fd76eb68a8e627576e8529be335cbd192973b21cf1c34702b3ff9afab6bde6454bd05abec322741f95bf4242c8baffaf48ed2a18
      - JWT_REFRESH_SECRET=71a0ffce065819b7147f467d28a0f7cf4181e2dd7f731d763a8cde357d9978519b11f3a68e60842c7a96a9879c04cebeac4a71f50ad9fd89752da5888ca4805d
      - FRONTEND_URL=http://frontend:5173
      - RABBITMQ_URL=amqp://rabbitmq
      - API_GATEWAY_KEY=996940d97b77a0bb9f7dbfbf6e8d8af5dfa6ca47250a3b2846d0272ca6eb741f
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  # 🚀 COURSE SERVICE
  course-service:
    build: ./backend/course-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/course-service
      - RABBITMQ_URL=amqp://rabbitmq
      - CLOUDINARY_CLOUD_NAME=value
      - CLOUDINARY_API_KEY=value
      - CLOUDINARY_API_SECRET=value
      - STRIPE_SECRET_KEY=value
      - API_GATEWAY_KEY=996940d97b77a0bb9f7dbfbf6e8d8af5dfa6ca47250a3b2846d0272ca6eb741f
      - TOKEN_SECRET=786d1bc21c5414a2f886bddad740386fe7d13f8efdde632c117846c769eaac6a4b13db59b26caac956786b3b9bed97099f991c8ef45ef6f9bdceeede030f8c29
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  # 🚀 BLOG SERVICE
  blog-service:
    build: ./backend/blog-service
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/blog-service
      - RABBITMQ_URL=amqp://rabbitmq
      - CLOUDINARY_CLOUD_NAME=value
      - CLOUDINARY_API_KEY=value
      - CLOUDINARY_API_SECRET=value
      - API_GATEWAY_KEY=996940d97b77a0bb9f7dbfbf6e8d8af5dfa6ca47250a3b2846d0272ca6eb741f
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  # 🚀 LIVE STREAMING SERVICE
  live-service:
    build: ./backend/live-service
    ports:
      - "5005:5005"
    environment:
      - API_GATEWAY_URL=http://api-gateway:5000
      - API_GATEWAY_KEY=996940d97b77a0bb9f7dbfbf6e8d8af5dfa6ca47250a3b2846d0272ca6eb741f
      - LIVE_SERVICE_URL=http://nginx-rtmp:1935
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - nginx-rtmp
      - rabbitmq
    networks:
      - app-network

  # 🚀 NGINX-RTMP (For Live Streaming)
  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./backend/live-service/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/live-service/hls:/hls
    networks:
      - app-network

  # 🚀 FFMPEG (For Encoding)
  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - nginx-rtmp
    restart: always
    privileged: true
    networks:
      - app-network

  # 🚀 NOTIFICATION SERVICE
  notification-service:
    build: ./backend/notification-service
    ports:
      - "5006:5006"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - EMAIL_USER=value
      - EMAIL_PASS=value
      - API_GATEWAY_KEY=996940d97b77a0bb9f7dbfbf6e8d8af5dfa6ca47250a3b2846d0272ca6eb741f
      - RABBITMQ_URL=amqp://rabbitmq
    networks:
      - app-network

  # 🚀 RABBITMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management dashboard
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🚀 MONGODB (Database)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 🚀 REDIS (For Caching and Notifications)
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
