app = 'prograbyte-auth-service'
primary_region = 'bom'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 50051
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls"]

[[vm]]
  size = 'shared-cpu-1x'
