# fly.toml app configuration file generated for prograbyte-user-service on 2025-06-30T14:36:13+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prograbyte-user-service'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
